### ISSUE TITLE
Recommended Interface

### ISSUE THREAD

**Issue by andrewthad** [chessai/freq#4]
When you add the optimized implementation, I would recommend providing an interface that includes at least the following (not necessarily with these names):

```haskell
data Freq -- optimal ByteArray-backed implementation
data FreqBuilder -- nested Map
instance Semigroup FreqBuilder
instance Monoid FreqBuilder

probability :: ByteString -> Freq -> Double
optimize :: FreqBuilder -> Freq
digram :: Word8 -> Word8 -> FreqBuilder
```

There are technically other possibilities (things like making a horrendously complicated `Monoid` instance for `Freq` or providing a function for turning a `ByteString` into a `Freq`/`FreqBuilder` or providing the `create` function you currently have), but none of them are strictly necessary as they wouldn't provide anything that couldn't be expressed with the above API. (They may provide performance advantages though).

**Comment by chessai** [comment]
should the second "instance Semigroup FreqBuilder" be "instance Monoid FreqBuilder"

**Comment by andrewthad** [comment]
Yes. I’m fixing this now.

**Comment by chessai** [comment]
This was done
