### ISSUE TITLE
Geometric Mean

### ISSUE THREAD

**Issue by andrewthad** [chessai/freq#8]
Today we discussed switching from arithmetic mean to geometric mean. This is better in most cases, but geometric mean has one tiny flaw: a single zero value knocks the whole mean down to zero. This is undesirable. Some quick googling reveals the following options:

- Ignore zeroes (terrible idea)
- Replace zero with surrogate value (ok idea)

The question becomes what to use for the surrogate. I think that rather than just picking a constant, it would be better to base it on the number of times the leading character occurred. For example, if we had the following frequencies:

```
N:
  A: 500
  C: 400
  D: 1100
O:
  A: 200
  B: 50
  C: 50
  D: 50
  F: 50
```

Anything missing would effectively be assigned the number 1. So, here is some probabilities would be calculated:

- `NA`: `500 / (500 + 400 + 1100)`
- `NB`: `1 / (500 + 400 + 1100)`
- `OE`: `1 / (200 + 50 + 50 + 50 + 50)`

This rewards missing pairs where the first letter is more generally uncommon.

I don't fully like this though. It means that the score of missing digrams gets lower as the corpus size gets bigger. It would be better if there was a way to fill in the missing digrams with something that would be about the same regardless of if the corpus size was 500,000 characters or 5,000,000 characters. Hmmm...

Maybe it could instead be based on the least common follower of the leading character. Or maybe on something else.

**Comment by andrewthad** [comment]
As another point in the design space, you may want to consider quadratic mean. Normally it has the problem of favoring a high values, but you could just invert everything first, then take the quadratic mean, then invert that  to get the final score. This has the advantage of not needing to use some kind of surrogate value for missing diagrams.

**Comment by andrewthad** [comment]
Some measurements:

```
>>> arithmeticMean xs = sum xs / fromIntegral (length (xs :: [Double]))
>>> geometricMean xs = product xs ** (1 / fromIntegral (length (xs :: [Double])))
>>> quadraticMean xs = (sum (map (^ (2 :: Int)) xs) / fromIntegral (length (xs :: [Double]))) ** 0.5
>>> inverseQuadraticMean xs = 1 - (sum (map (\x -> (1 - x) ^ (2 :: Int)) xs) / fromIntegral (length (xs :: [Double]))) ** 0.5
>>> import Numeric (showFFloat)
>>> arithmetic xs = putStr "Arithmetic: " >> putStrLn (showFFloat (Just 4) (arithmeticMean xs) "")
>>> geometric xs = putStr "Geometric: " >> putStrLn (showFFloat (Just 4) (geometricMean xs) "")
>>> quadratic xs = putStr "Quadratic: " >> putStrLn (showFFloat (Just 4) (quadraticMean xs) "")
>>> inverseQuadratic xs = putStr "Inverse Quadratic: " >> putStrLn (showFFloat (Just 4) (inverseQuadraticMean xs) "")
>>> run xs = arithmetic xs >> geometric xs >> quadratic xs >> inverseQuadratic xs
>>> run (replicate 8 0.12)
Arithmetic: 0.1200
Geometric: 0.1200
Quadratic: 0.1200
Inverse Quadratic: 0.1200
>>> run [0.20,0.30,0.01,0.20,0.05,0.07]
Arithmetic: 0.1383
Geometric: 0.0865
Quadratic: 0.1720
Inverse Quadratic: 0.1323
>>> run [0.01,0.01,0.01,0.01,0.01,0.15,0.24]
Arithmetic: 0.0629
Geometric: 0.0232
Quadratic: 0.1073
Inverse Quadratic: 0.0588
>>> run [0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.90]
Arithmetic: 0.1212
Geometric: 0.0176
Quadratic: 0.3183
Inverse Quadratic: 0.0733
>>> run [0.20,0.10,0.05,0.00,0.20]
Arithmetic: 0.1100
Geometric: 0.0000
Quadratic: 0.1360
Inverse Quadratic: 0.1064
```

Geometric mean seems to do better in every case except when there is a zero. This is maddening. I was hoping that inverse quadratic would do better than it actually does. It's less susceptible to skew that arithmetic mean, but it's still affected pretty badly. Hmmm...

**Comment by andrewthad** [comment]
Also, median is always an option. I think it might actually work better than all of the ones I tried out above.

**Comment by andrewthad** [comment]
The algorithm for finding median is pretty cool and runs in `O(n)` time.

**Comment by chessai** [comment]
reading paper related to this right now

**Comment by chessai** [comment]
```haskell
import Numeric (showFFloat)

arithmeticMean xs = sum xs / fromIntegral (length (xs :: [Double]))
geometricMean xs = product xs ** (1 / fromIntegral (length (xs :: [Double])))
quadraticMean xs = sqrt $ sum (map (\x -> x ** (2 :: Double)) xs) / fromIntegral (length (xs :: [Double]))
inverseQuadraticMean xs = 1 - (sum (map (\x -> (1 - x) ^ (2 :: Int)) xs) / fromIntegral (length (xs :: [Double]))) ** 0.5
arithmeticGeometricMean xs = (agmList xs) / fromIntegral (length (xs :: [Double]))

arithmetic xs = putStr "Arithmetic: " >> putStrLn (showFFloat (Just 4) (arithmeticMean xs) "")
arithmetic xs = putStr "Arithmetic: " >> putStrLn (showFFloat (Just 4) (arithmeticMean xs) "")
geometric xs = putStr "Geometric: " >> putStrLn (showFFloat (Just 4) (geometricMean xs) "")
quadratic xs = putStr "Quadratic: " >> putStrLn (showFFloat (Just 4) (quadraticMean xs) "")
inverseQuadratic xs = putStr "Inverse Quadratic: " >> putStrLn (showFFloat (Just 4) (inverseQuadraticMean xs) "")
arithmeticGeometric xs = putStr "Arithmetic-Geometric: " >> putStrLn (showFFloat (Just 4) (arithmeticGeometricMean xs) "")

run xs = arithmetic xs >> geometric xs >> quadratic xs >> inverseQuadratic xs >> arithmeticGeometric xs >> putStrLn ""

main = do
  run (replicate 8 0.12)
  run [0.20, 0.30, 0.01, 0.20, 0.05, 0.07]
  run [0.01, 0.01, 0.01, 0.01, 0.01, 0.15, 0.24]
  run [0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.90]
  run [0.20,0.10,0.05,0.00,0.20]

agmList [] = 0
agmList [x] = 0
agmList (x:y:xs) = agm x y + agmList (y:xs)

agm :: Double -> Double -> Double
agm x y = (pi / 4) * (x + y) / k (((x-y)/(x+y)) ** 2) 

k :: Double -> Double
k z = sum $ map (\(x,y) -> f x y) [(0,z),(1,z),(2,z),(3,z),(4,z),(5,z),(6,z)] 

f :: Double -> Double -> Double
f n k = factorial (2 * n) / ((2 ** (2 * n)) * ((factorial n) ** 2)) * (k ** (2 * n))

factorial :: Double -> Double
factorial 0 = 1
factorial 1 = 1
factorial n = n * factorial (n - 1)
```

**Comment by chessai** [comment]
```haskell
*Main> main
Arithmetic: 0.1200
Geometric: 0.1200
Quadratic: 0.1200
Inverse Quadratic: 0.1200
Arithmetic-Geometric: 0.1649

Arithmetic: 0.1383
Geometric: 0.0865
Quadratic: 0.1720
Inverse Quadratic: 0.1323
Arithmetic-Geometric: 0.1486

Arithmetic: 0.0629
Geometric: 0.0232
Quadratic: 0.1073
Inverse Quadratic: 0.0588
Arithmetic-Geometric: 0.0643

Arithmetic: 0.1212
Geometric: 0.0176
Quadratic: 0.3183
Inverse Quadratic: 0.0733
Arithmetic-Geometric: 0.0476

Arithmetic: 0.1100
Geometric: 0.0000
Quadratic: 0.1360
Inverse Quadratic: 0.1064
Arithmetic-Geometric: 0.0836
```

**Comment by andrewthad** [comment]
Arithmetic-Geometric mean looks more resistant to outliers than most of the others but still much less than geometric mean. From looking online, it seems like AGM is usually only applied to two numbers. It's also disheartening that:

    arithmeticGeometricMean [n,n,n] =/= n

I'm still leaning toward median as the best measure of central tendency here.

**Comment by andrewthad** [comment]
Also, you can use triple backticks to format larger code blocks in [github-flavored markdown](https://guides.github.com/features/mastering-markdown/).

**Comment by andrewthad** [comment]
Another idea: use more information available to us to make the geometric mean more palatable. Instead of just using the probability that `c2` follows `c1`, combine that probability with `min(prob(c1),prob(c2))`, the minimal probability that either of the characters showed up at all. The combining could be done with arithmetic mean or with AGM. Now there wouldn't be any zeroes to worry about (assuming that all characters in your string at least showed up anywhere in the training data).
